[project]
name = "demo-copilot"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "apo_huang", email = "apo_huang@cmoney.com.tw"},
]
dependencies = ["pydantic>=2.11.9"]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[dependency-groups]
test = [
    "pytest>=8.4.2",
]
[tool.pdm.scripts]
unit-test = "pytest tests/unit"
integration-test = "pytest tests/integration"